"""Initial migration with users and pdfs

Revision ID: 68dd8b8ce66d
Revises: fd9dc7c31d56
Create Date: 2025-11-30 01:16:25.936526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68dd8b8ce66d'
down_revision: Union[str, Sequence[str], None] = 'fd9dc7c31d56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
