"""Initial migration with users and pdfs

Revision ID: fd9dc7c31d56
Revises: 91cae2203d5f
Create Date: 2025-11-30 01:12:10.036710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd9dc7c31d56'
down_revision: Union[str, Sequence[str], None] = '91cae2203d5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pdf_documents', sa.Column('owner_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'pdf_documents', 'users', ['owner_id'], ['id'])
    op.drop_column('pdf_documents', 'page_count')
    op.drop_column('pdf_documents', 'extracted_text')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pdf_documents', sa.Column('extracted_text', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('pdf_documents', sa.Column('page_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'pdf_documents', type_='foreignkey')
    op.drop_column('pdf_documents', 'owner_id')
    # ### end Alembic commands ###
